// Generated by IcedCoffeeScript 1.7.1-e
(function() {
  var createHash, hash160;

  createHash = require('crypto').createHash;

  exports.hash160 = hash160 = function(x) {
    var rmd160, sha256, t;
    sha256 = createHash('sha256');
    rmd160 = createHash('rmd160');
    t = sha256.update(x).digest();
    return rmd160.update(t).digest();
  };

}).call(this);
