// Generated by IcedCoffeeScript 1.7.1-e
(function() {
  var hash160_to_bc_address, match1, match_script, opcodes;

  opcodes = require('./opcodes').opcodes;

  hash160_to_bc_address = require('./pubkey').hash160_to_bc_address;

  exports.match1 = match1 = function(o1, o2) {
    return (o1 <= opcodes.OP_PUSHDATA4 && o2 <= opcodes.OP_PUSHDATA4) || (o1 === o2);
  };

  exports.match_script = match_script = function(script, ops) {
    var i, ok, op, _i, _len;
    if (script.length === ops.length) {
      ok = true;
      for (i = _i = 0, _len = ops.length; _i < _len; i = ++_i) {
        op = ops[i];
        if (!match1(script[i][0], op)) {
          ok = false;
        }
      }
    } else {
      ok = false;
    }
    return ok;
  };

}).call(this);
